name: Bundle Size
description: Calculate bundle sizes for real-world Amplify JS use-cases

inputs:
  stack:
    description: Which tech stack to bundle against
    required: true
    default: 'webpack'

runs:
  using: 'composite'
  steps:
    - name: Install stack dependencies
      working-directory: ${{ github.action_path }}/${{ inputs.stack }}
      run: yarn install
      shell: bash

    - name: Calculate stack bundle sizes
      working-directory: ${{ github.action_path }}/${{ inputs.stack }}
      run: yarn calculate
      shell: bash
      env:
        CI_BRANCH_BASE: main
